// ===========================================================================
// うどんログ 店舗マスタデータ（全ページ共通の唯一のデータ元）
// ---------------------------------------------------------------------------
// このファイルは build-shops-data.py によって shops.csv から自動生成されます。
// 直接編集せず、shops.csv を編集して `python3 build-shops-data.py` を実行して
// ください。手で書き換えても、次回の生成で上書きされます。
// ===========================================================================

const SHOPS = [
  { id:1, name:"手打十段うどん バカ一代", kana:"ばかいちだい", city:"高松市", type:"セルフ", dish:"釜バター・ぶっかけ", hours:"6:00〜18:00", closed:"元旦", blog:"https://kagawan.com/udonbakaichidai/", parking:"あり（45台）" },
  { id:2, name:"本格手打もり家 高松本店", kana:"もりや", city:"高松市", type:"一般", dish:"" },
  { id:3, name:"本格手打もり家 高松シンボルタワー店", kana:"もりや", city:"高松市", type:"一般", dish:"" },
  { id:4, name:"はやし家製麺所 高松空港店", kana:"はやしや", city:"高松市", type:"製麺所", dish:"" },
  { id:5, name:"さぬき麺業 高松空港店", kana:"さぬきめんぎょう", city:"高松市", type:"一般", dish:"" },
  { id:6, name:"かわたうどん", kana:"かわた", city:"高松市", type:"一般", dish:"" },
  { id:7, name:"讃岐うどん 空海房", kana:"くうかいぼう", city:"高松市", type:"一般", dish:"" },
  { id:8, name:"麺処 綿谷 高松店", kana:"わたや", city:"高松市", type:"セルフ", dish:"" },
  { id:9, name:"根っこ 三谷店", kana:"ねっこ", city:"高松市", type:"一般", dish:"" },
  { id:10, name:"根っこ 空港通り店", kana:"ねっこ", city:"高松市", type:"一般", dish:"" },
  { id:11, name:"根っこ 鬼無店", kana:"ねっこ", city:"高松市", type:"一般", dish:"" },
  { id:12, name:"セルフうどんの店 竹清", kana:"ちくせい", city:"高松市", type:"セルフ", dish:"半熟卵天・ちくわ天" },
  { id:13, name:"讃岐うどん 一福 国分寺本店", kana:"いっぷく", city:"高松市", type:"一般", dish:"かけ・ぶっかけ" },
  { id:14, name:"晴屋製麺所 まちなか店", kana:"はれや", city:"高松市", type:"製麺所", dish:"" },
  { id:15, name:"晴屋製麺所 今里店", kana:"はれや", city:"高松市", type:"製麺所", dish:"" },
  { id:16, name:"おうどん 瀬戸晴れ", kana:"せとばれ", city:"高松市", type:"一般", dish:"" },
  { id:17, name:"饂飩家 五右衛門", kana:"ごえもん", city:"高松市", type:"一般", dish:"" },
  { id:18, name:"手打ちうどん 鶴丸", kana:"つるまる", city:"高松市", type:"一般", dish:"かけうどん・ざるうどん" },
  { id:19, name:"さか枝うどん 本店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"かけ・ぶっかけ" },
  { id:20, name:"さか枝うどん 春日店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"" },
  { id:21, name:"さか枝うどん 南新町店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"" },
  { id:22, name:"さか枝 仏生山店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"" },
  { id:23, name:"さか枝 多肥店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"" },
  { id:24, name:"ざいごうどん本家 わら家", kana:"わらや", city:"高松市", type:"一般", dish:"" },
  { id:25, name:"うどん本陣 山田家", kana:"やまだや", city:"高松市", type:"一般", dish:"" },
  { id:26, name:"手打ちうどん ひさ枝", kana:"ひさえ", city:"高松市", type:"一般", dish:"" },
  { id:27, name:"ヨコクラうどん", kana:"よこくら", city:"まんのう町", type:"一般", dish:"" },
  { id:28, name:"さぬきうどん 上原屋 本店", kana:"うえはらや", city:"高松市", type:"セルフ", dish:"ぶっかけ・かけうどん" },
  { id:29, name:"麺匠 くすがみ", kana:"くすがみ", city:"高松市", type:"一般", dish:"" },
  { id:30, name:"あづまうどん", kana:"あづま", city:"観音寺市", type:"一般", dish:"" },
  { id:31, name:"うつ海うどん", kana:"うつみ", city:"三豊市", type:"一般", dish:"" },
  { id:32, name:"高松満福", kana:"まんぷく", city:"高松市", type:"一般", dish:"" },
  { id:33, name:"手打うどん 三徳", kana:"さんとく", city:"高松市", type:"一般", dish:"かけ・ざる" },
  { id:34, name:"中西うどん", kana:"なかにし", city:"高松市", type:"一般", dish:"" },
  { id:35, name:"手打ちうどん 清水屋", kana:"しみずや", city:"高松市", type:"一般", dish:"" },
  { id:36, name:"宮武うどん", kana:"みやたけ", city:"琴平町", type:"一般", dish:"" },
  { id:37, name:"UDON 山もり", kana:"やまもり", city:"高松市", type:"一般", dish:"" },
  { id:38, name:"手打麺や 大島", kana:"おおしま", city:"高松市", type:"一般", dish:"" },
  { id:39, name:"がもううどん", kana:"がもう", city:"坂出市", type:"製麺所", dish:"かけうどん・釜玉" },
  { id:40, name:"日の出製麺所", kana:"ひので", city:"坂出市", type:"製麺所", dish:"かけうどん" },
  { id:41, name:"山下うどん", kana:"やました", city:"坂出市", type:"一般", dish:"ぶっかけ" },
  { id:42, name:"めんや七福 別邸", kana:"しちふく", city:"高松市", type:"一般", dish:"" },
  { id:43, name:"讃岐うどん やなぎ屋 西大浜店", kana:"やなぎや", city:"坂出市", type:"一般", dish:"" },
  { id:44, name:"架け橋 夢うどん", kana:"ゆめ", city:"坂出市", type:"一般", dish:"かけうどん" },
  { id:45, name:"山越うどん", kana:"やまごえ", city:"綾川町", type:"製麺所", dish:"釜玉・かけうどん" },
  { id:46, name:"手打うどん田村", kana:"たむら", city:"綾川町", type:"製麺所", dish:"かけうどん・ぶっかけ" },
  { id:47, name:"本格手打うどん はゆか", kana:"はゆか", city:"三豊市", type:"一般", dish:"" },
  { id:48, name:"池内うどん店", kana:"いけうち", city:"高松市", type:"一般", dish:"" },
  { id:49, name:"いなもくうどん", kana:"いなもく", city:"高松市", type:"一般", dish:"" },
  { id:50, name:"釜あげうどん 長田 in 香の香", kana:"ながた", city:"善通寺市", type:"製麺所", dish:"釜揚げうどん" },
  { id:51, name:"山下うどん", kana:"やました", city:"善通寺市", type:"一般", dish:"ぶっかけ" },
  { id:52, name:"宮川製麺所", kana:"みやがわ", city:"坂出市", type:"製麺所", dish:"かけうどん・ざる" },
  { id:53, name:"白川うどん", kana:"しらかわ", city:"高松市", type:"一般", dish:"" },
  { id:54, name:"本格手打 あかみち", kana:"あかみち", city:"高松市", type:"一般", dish:"" },
  { id:55, name:"セルフうどん こだわり八輻", kana:"こだわりやわら", city:"高松市", type:"セルフ", dish:"" },
  { id:56, name:"あやうた製麺", kana:"あやうた", city:"丸亀市", type:"製麺所", dish:"" },
  { id:57, name:"麦香うどん", kana:"むぎか", city:"高松市", type:"一般", dish:"" },
  { id:58, name:"讃岐うどん海侍其の壱", kana:"かいじ", city:"高松市", type:"一般", dish:"" },
  { id:59, name:"純手打うどん よしや", kana:"よしや", city:"綾川町", type:"一般", dish:"かけうどん" },
  { id:60, name:"セルフうどん おかだ", kana:"おかだ", city:"高松市", type:"セルフ", dish:"" },
  { id:61, name:"なかむらうどん", kana:"なかむら", city:"丸亀市", type:"製麺所", dish:"釜玉・釜あげ" },
  { id:62, name:"麺処 綿谷 丸亀店", kana:"わたや", city:"丸亀市", type:"セルフ", dish:"牛肉うどん・肉ぶっかけ" },
  { id:63, name:"元祖しょうゆうどん 小縣家", kana:"おがたや", city:"琴平町", type:"一般", dish:"根っこうどん" },
  { id:64, name:"谷川米穀店", kana:"たにがわ", city:"まんのう町", type:"製麺所", dish:"" },
  { id:65, name:"三嶋製麺所", kana:"みしま", city:"三豊市", type:"製麺所", dish:"かけうどん" },
  { id:66, name:"山内うどん", kana:"やまうち", city:"まんのう町", type:"製麺所", dish:"かけうどん・釜あげ" },
  { id:67, name:"うどん そらいけ", kana:"そらいけ", city:"高松市", type:"一般", dish:"" },
  { id:68, name:"さぬきうどん羽立", kana:"はだち", city:"高松市", type:"一般", dish:"" },
  { id:69, name:"さぬきうどん 溜", kana:"たまり", city:"高松市", type:"一般", dish:"" },
  { id:70, name:"八十八庵", kana:"やそばあん", city:"さぬき市", type:"一般", dish:"" },
  { id:71, name:"さぬきうどん処 麺でぃ〜", kana:"めんでぃ", city:"高松市", type:"一般", dish:"" },
  { id:72, name:"麺処 まはろ", kana:"まはろ", city:"高松市", type:"一般", dish:"" },
  { id:73, name:"手打うどん まるたけ", kana:"まるたけ", city:"高松市", type:"一般", dish:"" },
  { id:74, name:"いけこうどん", kana:"いけこ", city:"高松市", type:"一般", dish:"" },
  { id:75, name:"根ッ子うどん", kana:"ねっこ", city:"高松市", type:"一般", dish:"", status:"閉店" },
  { id:76, name:"手打ちうどん むさし", kana:"むさし", city:"高松市", type:"一般", dish:"" },
  { id:77, name:"須崎食料品店", kana:"すさき", city:"三豊市", type:"製麺所", dish:"かけうどん・ぶっかけ" },
  { id:78, name:"うどんや カマ喜ri", kana:"かまきり", city:"高松市", type:"一般", dish:"" },
  { id:79, name:"うまじ家 豊浜店", kana:"うまじや", city:"観音寺市", type:"一般", dish:"" },
  { id:80, name:"手織うどん 滝音", kana:"たきおと", city:"高松市", type:"一般", dish:"" },
  { id:81, name:"多田製麺所", kana:"ただ", city:"高松市", type:"製麺所", dish:"" },
  { id:82, name:"めりけんや", kana:"めりけんや", city:"高松市", type:"セルフ", dish:"ぶっかけ・かけうどん" },
  { id:83, name:"池上製麺所", kana:"いけがみ", city:"高松市", type:"製麺所", dish:"釜玉・かけうどん" },
  { id:84, name:"うどん棒 本店", kana:"うどんぼう", city:"高松市", type:"一般", dish:"おろしぶっかけ" },
  { id:85, name:"春日うどん", kana:"かすが", city:"高松市", type:"一般", dish:"かけ・ざる" },
  { id:86, name:"手打ちうどん いわせ", kana:"いわせ", city:"高松市", type:"一般", dish:"かけうどん" },
  { id:87, name:"手打ちうどん 研や", kana:"けんや", city:"高松市", type:"一般", dish:"ぶっかけ・かけ" },
  { id:88, name:"ふるさとうどん", kana:"ふるさと", city:"高松市", type:"セルフ", dish:"かけ・釜玉" },
  { id:89, name:"手打ちうどん 大介", kana:"だいすけ", city:"高松市", type:"一般", dish:"かけうどん" },
  { id:90, name:"谷川製麺所", kana:"たにがわ", city:"高松市", type:"製麺所", dish:"かけうどん" },
  { id:91, name:"大橋屋", kana:"おおはしや", city:"丸亀市", type:"一般", dish:"ひやかけ" },
  { id:92, name:"彦江製麺所", kana:"ひこえ", city:"丸亀市", type:"製麺所", dish:"かけうどん" },
  { id:93, name:"手打ちうどん 渡辺", kana:"わたなべ", city:"丸亀市", type:"一般", dish:"ぶっかけ・かけ" },
  { id:94, name:"手打ちうどん 岡じま", kana:"おかじま", city:"坂出市", type:"一般", dish:"かけ・ぶっかけ" },
  { id:95, name:"手打ちうどん 芳野", kana:"よしの", city:"善通寺市", type:"一般", dish:"かけ・ひやかけ" },
  { id:96, name:"手打ちうどん こんぴら家", kana:"こんぴらや", city:"琴平町", type:"一般", dish:"かけ・ざる" },
  { id:97, name:"上杉食品", kana:"うえすぎ", city:"まんのう町", type:"製麺所", dish:"かけうどん" },
  { id:98, name:"手打ちうどん たむら", kana:"たむら", city:"三豊市", type:"一般", dish:"かけ・ざる" },
  { id:99, name:"本格手打うどん 長谷", kana:"はせ", city:"三豊市", type:"一般", dish:"かけうどん" },
  { id:100, name:"手打ちうどん 大将", kana:"たいしょう", city:"観音寺市", type:"一般", dish:"かけうどん" },
  { id:101, name:"てっちゃんうどん", kana:"てっちゃん", city:"観音寺市", type:"セルフ", dish:"かけ・ぶっかけ" },
  { id:102, name:"恵比須", kana:"えびす", city:"さぬき市", type:"一般", dish:"かけうどん・ぶっかけ" },
  { id:103, name:"手打ちうどん 藤井", kana:"ふじい", city:"さぬき市", type:"一般", dish:"かけうどん" },
  { id:104, name:"手打ちうどん 大庄屋", kana:"おおしょうや", city:"三木町", type:"一般", dish:"かけ・ざる" },
  { id:105, name:"三木SA うどん店", kana:"みき", city:"三木町", type:"セルフ", dish:"かけうどん" },
  { id:106, name:"手打ちうどん 三昧", kana:"ざんまい", city:"東かがわ市", type:"一般", dish:"かけ・ぶっかけ" },
  { id:107, name:"手打ちうどん 寒川", kana:"さんがわ", city:"東かがわ市", type:"一般", dish:"かけうどん" },
  { id:108, name:"手打ちうどん 多度津家", kana:"たどつや", city:"多度津町", type:"一般", dish:"かけうどん" },
];
