// ===========================================================================
// うどログ 店舗マスタデータ（全ページ共通の唯一のデータ元）
// ---------------------------------------------------------------------------
// このファイルは build-shops-data.py によって shops.csv から自動生成されます。
// 直接編集せず、shops.csv を編集して `python3 build-shops-data.py` を実行して
// ください。手で書き換えても、次回の生成で上書きされます。
// ===========================================================================

const SHOPS = [
  { id:1, name:"手打十段うどん バカ一代", kana:"ばかいちだい", city:"高松市", type:"セルフ", dish:"釜バター・ぶっかけ", hours:"6:00〜18:00", closed:"元旦", blog:"https://kagawan.com/udonbakaichidai/", parking:"あり（45台）", slug:"udonbakaichidai" },
  { id:2, name:"本格手打もり家 高松本店", kana:"もりや", city:"高松市", type:"一般", dish:"", slug:"moriya" },
  { id:3, name:"本格手打もり家 高松シンボルタワー店", kana:"もりや", city:"高松市", type:"一般", dish:"", slug:"moriya-3" },
  { id:4, name:"はやし家製麺所 高松空港店", kana:"はやしや", city:"高松市", type:"製麺所", dish:"", slug:"hayashiya" },
  { id:5, name:"さぬき麺業 高松空港店", kana:"さぬきめんぎょう", city:"高松市", type:"一般", dish:"", slug:"sanukimengyou" },
  { id:6, name:"かわたうどん", kana:"かわた", city:"高松市", type:"一般", dish:"", slug:"kawata" },
  { id:7, name:"讃岐うどん 空海房", kana:"くうかいぼう", city:"高松市", type:"一般", dish:"", slug:"kuukaibou" },
  { id:8, name:"麺処 綿谷 高松店", kana:"わたや", city:"高松市", type:"セルフ", dish:"", slug:"wataya" },
  { id:9, name:"根っこ 三谷店", kana:"ねっこ", city:"高松市", type:"一般", dish:"", slug:"nekko" },
  { id:10, name:"根っこ 空港通り店", kana:"ねっこ", city:"高松市", type:"一般", dish:"", slug:"nekko-10" },
  { id:11, name:"根っこ 鬼無店", kana:"ねっこ", city:"高松市", type:"一般", dish:"", slug:"nekko-11" },
  { id:12, name:"セルフうどんの店 竹清", kana:"ちくせい", city:"高松市", type:"セルフ", dish:"半熟卵天・ちくわ天", slug:"chikusei" },
  { id:13, name:"讃岐うどん 一福 国分寺本店", kana:"いっぷく", city:"高松市", type:"一般", dish:"かけ・ぶっかけ", slug:"ippuku" },
  { id:14, name:"晴屋製麺所 まちなか店", kana:"はれや", city:"高松市", type:"製麺所", dish:"", slug:"hareya" },
  { id:15, name:"晴屋製麺所 今里店", kana:"はれや", city:"高松市", type:"製麺所", dish:"", slug:"hareya-15" },
  { id:16, name:"おうどん 瀬戸晴れ", kana:"せとばれ", city:"高松市", type:"一般", dish:"", slug:"setobare" },
  { id:17, name:"饂飩家 五右衛門", kana:"ごえもん", city:"高松市", type:"一般", dish:"", slug:"goemon" },
  { id:18, name:"手打ちうどん 鶴丸", kana:"つるまる", city:"高松市", type:"一般", dish:"かけうどん・ざるうどん", slug:"tsurumaru" },
  { id:19, name:"さか枝うどん 本店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"かけ・ぶっかけ", slug:"sakaeda" },
  { id:20, name:"さか枝うどん 春日店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"", slug:"sakaeda-20" },
  { id:21, name:"さか枝うどん 南新町店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"", slug:"sakaeda-21" },
  { id:22, name:"さか枝 仏生山店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"", slug:"sakaeda-22" },
  { id:23, name:"さか枝 多肥店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"", slug:"sakaeda-23" },
  { id:24, name:"ざいごうどん本家 わら家", kana:"わらや", city:"高松市", type:"一般", dish:"", slug:"waraya" },
  { id:25, name:"うどん本陣 山田家", kana:"やまだや", city:"高松市", type:"一般", dish:"", slug:"yamadaya" },
  { id:26, name:"手打ちうどん ひさ枝", kana:"ひさえ", city:"高松市", type:"一般", dish:"", slug:"hisae" },
  { id:27, name:"ヨコクラうどん", kana:"よこくら", city:"まんのう町", type:"一般", dish:"", slug:"yokokura" },
  { id:28, name:"さぬきうどん 上原屋 本店", kana:"うえはらや", city:"高松市", type:"セルフ", dish:"ぶっかけ・かけうどん", slug:"ueharaya" },
  { id:29, name:"麺匠 くすがみ", kana:"くすがみ", city:"高松市", type:"一般", dish:"", slug:"kusugami" },
  { id:30, name:"あづまうどん", kana:"あづま", city:"観音寺市", type:"一般", dish:"", slug:"azuma" },
  { id:31, name:"うつ海うどん", kana:"うつみ", city:"三豊市", type:"一般", dish:"", slug:"utsumi" },
  { id:32, name:"高松満福", kana:"まんぷく", city:"高松市", type:"一般", dish:"", slug:"manpuku" },
  { id:33, name:"手打うどん 三徳", kana:"さんとく", city:"高松市", type:"一般", dish:"かけ・ざる", slug:"santoku" },
  { id:34, name:"中西うどん", kana:"なかにし", city:"高松市", type:"一般", dish:"", slug:"nakanishi" },
  { id:35, name:"手打ちうどん 清水屋", kana:"しみずや", city:"高松市", type:"一般", dish:"", slug:"shimizuya" },
  { id:36, name:"宮武うどん", kana:"みやたけ", city:"琴平町", type:"一般", dish:"", slug:"miyatake" },
  { id:37, name:"UDON 山もり", kana:"やまもり", city:"高松市", type:"一般", dish:"", slug:"yamamori" },
  { id:38, name:"手打麺や 大島", kana:"おおしま", city:"高松市", type:"一般", dish:"", slug:"ooshima" },
  { id:39, name:"がもううどん", kana:"がもう", city:"坂出市", type:"製麺所", dish:"かけうどん・釜玉", slug:"gamou" },
  { id:40, name:"日の出製麺所", kana:"ひので", city:"坂出市", type:"製麺所", dish:"かけうどん", slug:"hinode" },
  { id:41, name:"山下うどん", kana:"やました", city:"坂出市", type:"一般", dish:"ぶっかけ", slug:"yamashita" },
  { id:42, name:"めんや七福 別邸", kana:"しちふく", city:"高松市", type:"一般", dish:"", slug:"shichifuku" },
  { id:43, name:"讃岐うどん やなぎ屋 西大浜店", kana:"やなぎや", city:"坂出市", type:"一般", dish:"", slug:"yanagiya" },
  { id:44, name:"架け橋 夢うどん", kana:"ゆめ", city:"坂出市", type:"一般", dish:"かけうどん", slug:"yume" },
  { id:45, name:"山越うどん", kana:"やまごえ", city:"綾川町", type:"製麺所", dish:"釜玉・かけうどん", hours:"9:00〜13:30", closed:"水・日曜（GW/盆/正月は臨時休あり）", blog:"https://kagawan.com/yamagoeudon/", parking:"あり（200台）", slug:"yamagoeudon" },
  { id:46, name:"手打うどん田村", kana:"たむら", city:"綾川町", type:"一般", dish:"かけうどん・ぶっかけ", hours:"9:00〜13:00（売り切れ次第終了）", closed:"日曜・祝日", blog:"https://kagawan.com/tamuraudon/", parking:"あり（30台）", slug:"tamuraudon" },
  { id:47, name:"本格手打うどん はゆか", kana:"はゆか", city:"綾川町", type:"セルフ", dish:"", hours:"10:00〜15:30", closed:"月曜（祝日は営業）", blog:"https://kagawan.com/hayuka/", parking:"あり（23台）", slug:"hayuka" },
  { id:48, name:"池内うどん店", kana:"いけうち", city:"綾川町", type:"製麺所", dish:"", hours:"7:00〜13:00（売り切れ次第終了）", closed:"月・金曜", blog:"https://kagawan.com/ikeuchiudonten/", parking:"あり（店の東側倉庫前）", slug:"ikeuchiudonten" },
  { id:49, name:"いなもくうどん", kana:"いなもく", city:"綾川町", type:"一般", dish:"", hours:"10:30〜14:00（玉切れ次第終了）", closed:"木曜・第2水曜（祝日は営業・翌日休）", blog:"https://kagawan.com/inamokuudon/", parking:"あり（10台）", slug:"inamokuudon" },
  { id:50, name:"釜あげうどん 長田 in 香の香", kana:"ながた", city:"善通寺市", type:"一般", dish:"釜揚げうどん", hours:"9:00〜15:00（玉切れの際は早じまい）", closed:"水・木曜（祝日は営業）", blog:"https://kagawan.com/nagata-in-kanoka/", parking:"あり（160台・大型バス可）", slug:"nagata-in-kanoka" },
  { id:51, name:"山下うどん", kana:"やました", city:"善通寺市", type:"セルフ", dish:"ぶっかけ", hours:"9:30〜16:00（売り切れ次第終了）", closed:"火曜（祝日は営業・翌水曜休）", blog:"https://kagawan.com/yamashitaudon-zentsuji/", parking:"あり（50台）", slug:"yamashitaudon-zentsuji" },
  { id:52, name:"宮川製麺所", kana:"みやがわ", city:"善通寺市", type:"製麺所", dish:"かけうどん・ざる", hours:"8:00〜18:00（売り切れ次第終了）", closed:"日曜", blog:"https://kagawan.com/miyagawa-seimenjyo/", parking:"あり（30台）", slug:"miyagawa-seimenjyo" },
  { id:53, name:"白川うどん", kana:"しらかわ", city:"善通寺市", type:"一般", dish:"", hours:"9:30〜15:00（売り切れ次第終了）", closed:"火曜（祝日は営業・翌日休）・第3水曜", blog:"https://kagawan.com/sirakawaudon/", parking:"あり（30台）", slug:"sirakawaudon" },
  { id:54, name:"本格手打 あかみち", kana:"あかみち", city:"善通寺市", type:"一般", dish:"", hours:"10:00〜15:00（玉切れ次第終了）※一部土曜は夜18:00〜20:00", closed:"水・木曜", blog:"https://kagawan.com/akamichi/", parking:"あり（25台）", slug:"akamichi" },
  { id:55, name:"セルフうどん こだわり八輻", kana:"こだわりやわら", city:"善通寺市", type:"セルフ", dish:"", hours:"11:00〜14:00", closed:"火・金曜", blog:"https://kagawan.com/hachiya/", parking:"あり（30台）", slug:"hachiya" },
  { id:56, name:"あやうた製麺", kana:"あやうた", city:"丸亀市", type:"セルフ", dish:"", hours:"11:00〜14:00", closed:"金曜", blog:"https://kagawan.com/ayautaseimen/", parking:"あり（25台）", slug:"ayautaseimen" },
  { id:57, name:"麦香うどん", kana:"むぎか", city:"丸亀市", type:"一般", dish:"", hours:"10:00〜15:00", closed:"水曜", blog:"https://kagawan.com/bakuka-udon/", parking:"あり（15台）", slug:"bakuka-udon" },
  { id:58, name:"讃岐うどん海侍其の壱", kana:"かいじ", city:"丸亀市", type:"セルフ", dish:"", hours:"9:00〜14:00", closed:"月曜（祝日は翌火曜）", blog:"https://kagawan.com/kaiji/", parking:"あり（店舗横）", slug:"kaiji" },
  { id:59, name:"純手打うどん よしや", kana:"よしや", city:"丸亀市", type:"一般", dish:"かけうどん", hours:"7:00〜14:50（売り切れ次第終了）", closed:"火曜", blog:"https://kagawan.com/jyunteuchiudon-yoshiya/", parking:"あり（15台）", slug:"jyunteuchiudon-yoshiya" },
  { id:60, name:"セルフうどん おかだ", kana:"おかだ", city:"丸亀市", type:"セルフ", dish:"", hours:"飲食 10:30〜14:00／土産 9:00〜17:00", closed:"土・日・祝", blog:"https://kagawan.com/selfudonokada/", parking:"あり（33台）", slug:"selfudonokada" },
  { id:61, name:"なかむらうどん", kana:"なかむら", city:"丸亀市", type:"セルフ", dish:"釜玉・釜あげ", hours:"9:00〜14:00", closed:"火曜", blog:"https://kagawan.com/hiragana-nakamuraudon/", parking:"あり（40台）", slug:"hiragana-nakamuraudon" },
  { id:62, name:"麺処 綿谷 丸亀店", kana:"わたや", city:"丸亀市", type:"セルフ", dish:"牛肉うどん・肉ぶっかけ", hours:"8:30〜14:00（売り切れ次第終了）", closed:"日曜・祝日", blog:"https://kagawan.com/wataya/", parking:"あり（50台）", slug:"wataya-62" },
  { id:63, name:"元祖しょうゆうどん 小縣家", kana:"おがたや", city:"まんのう町", type:"一般", dish:"根っこうどん", hours:"10:30〜14:30", closed:"月・火曜", blog:"https://kagawan.com/ogataya/", parking:"あり（40台）", slug:"ogataya" },
  { id:64, name:"谷川米穀店", kana:"たにがわ", city:"まんのう町", type:"製麺所", dish:"", hours:"10:30〜13:30", closed:"日曜", blog:"https://kagawan.com/tanikawabeikokuten/", parking:"あり", slug:"tanikawabeikokuten" },
  { id:65, name:"三嶋製麺所", kana:"みしま", city:"まんのう町", type:"製麺所", dish:"かけうどん", hours:"平日 9:00〜16:30／土日 9:00〜16:00", closed:"金曜", blog:"https://kagawan.com/mishimaseimenjo/", parking:"あり（3台）", slug:"mishimaseimenjo" },
  { id:66, name:"山内うどん", kana:"やまうち", city:"まんのう町", type:"一般", dish:"かけうどん・釜あげ", hours:"9:00〜13:30（玉切れ次第終了）", closed:"木曜", blog:"https://kagawan.com/yamauchiudon/", parking:"あり（約30台）", slug:"yamauchiudon" },
  { id:67, name:"うどん そらいけ", kana:"そらいけ", city:"さぬき市", type:"一般", dish:"", hours:"11:00〜14:00", closed:"日曜", blog:"https://kagawan.com/soraike/", parking:"あり（3台）", slug:"soraike" },
  { id:68, name:"さぬきうどん羽立", kana:"はだち", city:"さぬき市", type:"セルフ", dish:"", hours:"10:00〜14:00", closed:"金曜", blog:"https://kagawan.com/haryu/", parking:"あり（8台）", slug:"haryu" },
  { id:69, name:"さぬきうどん 溜", kana:"たまり", city:"さぬき市", type:"セルフ", dish:"", hours:"10:00〜15:00", closed:"年中無休", blog:"https://kagawan.com/tamariudon/", parking:"あり（無料・約150台）", slug:"tamariudon" },
  { id:70, name:"八十八庵", kana:"やそばあん", city:"さぬき市", type:"一般", dish:"", hours:"8:00〜16:30（LO16:00）", closed:"12/30・31のみ休み", blog:"https://kagawan.com/yasobaan/", parking:"あり（60台）", slug:"yasobaan" },
  { id:71, name:"さぬきうどん処 麺でぃ〜", kana:"めんでぃ", city:"さぬき市", type:"一般", dish:"", hours:"10:30〜15:00", closed:"月曜（祝日は営業・翌火曜休）", blog:"https://kagawan.com/udondokoro-mendy/", parking:"あり（3カ所）", slug:"udondokoro-mendy" },
  { id:72, name:"麺処 まはろ", kana:"まはろ", city:"さぬき市", type:"一般", dish:"", hours:"平日 11:00〜14:00／土日祝 10:30〜15:00（玉切れ次第終了）", closed:"水曜（祝日は営業・翌木曜休）", blog:"https://kagawan.com/maharo/", parking:"あり（無料・約20台）", slug:"maharo" },
  { id:73, name:"手打うどん まるたけ", kana:"まるたけ", city:"さぬき市", type:"セルフ", dish:"", hours:"9:00〜15:00", closed:"土・日曜", blog:"https://kagawan.com/marutakeudon/", parking:"あり（13台）", slug:"marutakeudon" },
  { id:74, name:"いけこうどん", kana:"いけこ", city:"多度津町", type:"一般", dish:"", hours:"10:00〜15:00", closed:"月曜", blog:"https://kagawan.com/ikekoudon/", parking:"あり（約14台）", slug:"ikekoudon" },
  { id:75, name:"根ッ子うどん", kana:"ねっこ", city:"多度津町", type:"セルフ", dish:"", hours:"10:30〜14:00", closed:"水曜", status:"閉店", blog:"https://kagawan.com/nekkoudon/", parking:"あり（約20台）", slug:"nekkoudon" },
  { id:76, name:"手打ちうどん むさし", kana:"むさし", city:"琴平町", type:"一般", dish:"", hours:"10:00〜15:00／17:00〜20:00", closed:"月・火曜", blog:"https://kagawan.com/musashi/", parking:"あり（無料・共同195台）", slug:"musashi" },
  { id:77, name:"須崎食料品店", kana:"すさき", city:"三豊市", type:"製麺所", dish:"かけうどん・ぶっかけ", hours:"9:00〜11:30", closed:"水曜（臨時休業あり）", blog:"https://kagawan.com/suzakishokuryohinten/", parking:"あり（約38台）", slug:"suzakishokuryohinten" },
  { id:78, name:"うどんや カマ喜ri", kana:"かまきり", city:"観音寺市", type:"一般", dish:"", hours:"11:00〜14:00（玉切れ次第終了）", closed:"日曜", blog:"https://kagawan.com/kamakiri/", parking:"あり（約20台）", slug:"kamakiri" },
  { id:79, name:"うまじ家 豊浜店", kana:"うまじや", city:"観音寺市", type:"セルフ", dish:"", hours:"10:00〜13:30", closed:"なし", blog:"https://kagawan.com/umajiya-toyohama/", parking:"あり（19台）", slug:"umajiya-toyohama" },
  { id:80, name:"手織うどん 滝音", kana:"たきおと", city:"三木町", type:"一般", dish:"", hours:"10:00〜15:00", closed:"月曜（祝日は営業・翌火曜休）", blog:"https://kagawan.com/takine/", parking:"あり（64台）", slug:"takine" },
  { id:81, name:"多田製麺所", kana:"ただ", city:"三木町", type:"製麺所", dish:"", hours:"8:00〜15:00", closed:"火曜", blog:"https://kagawan.com/tadaseimenjo/", parking:"あり（第一3台・第二あり）", slug:"tadaseimenjo" },
  { id:82, name:"めりけんや", kana:"めりけんや", city:"高松市", type:"セルフ", dish:"ぶっかけ・かけうどん", slug:"merikenya" },
  { id:83, name:"池上製麺所", kana:"いけがみ", city:"高松市", type:"製麺所", dish:"釜玉・かけうどん", slug:"ikegami" },
  { id:84, name:"うどん棒 本店", kana:"うどんぼう", city:"高松市", type:"一般", dish:"おろしぶっかけ", slug:"udonbou" },
  { id:85, name:"春日うどん", kana:"かすが", city:"高松市", type:"一般", dish:"かけ・ざる", slug:"kasuga" },
  { id:86, name:"手打ちうどん いわせ", kana:"いわせ", city:"高松市", type:"一般", dish:"かけうどん", slug:"iwase" },
  { id:87, name:"手打ちうどん 研や", kana:"けんや", city:"高松市", type:"一般", dish:"ぶっかけ・かけ", slug:"kenya" },
  { id:88, name:"ふるさとうどん", kana:"ふるさと", city:"高松市", type:"セルフ", dish:"かけ・釜玉", slug:"furusato" },
  { id:89, name:"手打ちうどん 大介", kana:"だいすけ", city:"高松市", type:"一般", dish:"かけうどん", slug:"daisuke" },
  { id:90, name:"谷川製麺所", kana:"たにがわ", city:"高松市", type:"製麺所", dish:"かけうどん", slug:"tanigawa" },
  { id:91, name:"大橋屋", kana:"おおはしや", city:"丸亀市", type:"一般", dish:"ひやかけ", slug:"oohashiya" },
  { id:92, name:"彦江製麺所", kana:"ひこえ", city:"丸亀市", type:"製麺所", dish:"かけうどん", slug:"hikoe" },
  { id:93, name:"手打ちうどん 渡辺", kana:"わたなべ", city:"丸亀市", type:"一般", dish:"ぶっかけ・かけ", slug:"watanabe" },
  { id:94, name:"手打ちうどん 岡じま", kana:"おかじま", city:"坂出市", type:"一般", dish:"かけ・ぶっかけ", slug:"okajima" },
  { id:95, name:"手打ちうどん 芳野", kana:"よしの", city:"善通寺市", type:"一般", dish:"かけ・ひやかけ", slug:"yoshino" },
  { id:96, name:"手打ちうどん こんぴら家", kana:"こんぴらや", city:"琴平町", type:"一般", dish:"かけ・ざる", slug:"konpiraya" },
  { id:97, name:"上杉食品", kana:"うえすぎ", city:"まんのう町", type:"製麺所", dish:"かけうどん", slug:"uesugi" },
  { id:98, name:"手打ちうどん たむら", kana:"たむら", city:"三豊市", type:"一般", dish:"かけ・ざる", slug:"tamura" },
  { id:99, name:"本格手打うどん 長谷", kana:"はせ", city:"三豊市", type:"一般", dish:"かけうどん", slug:"hase" },
  { id:100, name:"手打ちうどん 大将", kana:"たいしょう", city:"観音寺市", type:"一般", dish:"かけうどん", slug:"taishou" },
  { id:101, name:"てっちゃんうどん", kana:"てっちゃん", city:"観音寺市", type:"セルフ", dish:"かけ・ぶっかけ", slug:"tecchan" },
  { id:102, name:"恵比須", kana:"えびす", city:"さぬき市", type:"一般", dish:"かけうどん・ぶっかけ", slug:"ebisu" },
  { id:103, name:"手打ちうどん 藤井", kana:"ふじい", city:"さぬき市", type:"一般", dish:"かけうどん", slug:"fujii" },
  { id:104, name:"手打ちうどん 大庄屋", kana:"おおしょうや", city:"三木町", type:"一般", dish:"かけ・ざる", slug:"ooshouya" },
  { id:105, name:"三木SA うどん店", kana:"みき", city:"三木町", type:"セルフ", dish:"かけうどん", slug:"miki" },
  { id:106, name:"手打ちうどん 三昧", kana:"ざんまい", city:"東かがわ市", type:"一般", dish:"かけ・ぶっかけ", slug:"zanmai" },
  { id:107, name:"手打ちうどん 寒川", kana:"さんがわ", city:"東かがわ市", type:"一般", dish:"かけうどん", slug:"sangawa" },
  { id:108, name:"手打ちうどん 多度津家", kana:"たどつや", city:"多度津町", type:"一般", dish:"かけうどん", slug:"tadotsuya" },
];
