// ===========================================================================
// うどログ 店舗マスタデータ（全ページ共通の唯一のデータ元）
// ---------------------------------------------------------------------------
// このファイルは build-shops-data.py によって shops.csv から自動生成されます。
// 直接編集せず、shops.csv を編集して `python3 build-shops-data.py` を実行して
// ください。手で書き換えても、次回の生成で上書きされます。
// ===========================================================================

const SHOPS = [
  { id:1, name:"手打十段うどん バカ一代", kana:"ばかいちだい", city:"高松市", type:"セルフ", dish:"", hours:"6:00〜18:00", closed:"元旦", blog:"https://kagawan.com/udonbakaichidai/", parking:"あり（45台）", slug:"udonbakaichidai" },
  { id:2, name:"本格手打もり家 高松本店", kana:"もりや", city:"高松市", type:"一般", dish:"", hours:"10:30〜18:00", closed:"木・金曜（祝日は営業）", blog:"https://kagawan.com/moriya/", parking:"あり（40台）", slug:"moriya" },
  { id:3, name:"本格手打もり家 高松シンボルタワー店", kana:"もりや", city:"高松市", type:"一般", dish:"", hours:"昼 11:00〜15:00／夜 17:00〜21:00", closed:"火曜（祝日営業）・第1・第3月曜", blog:"https://kagawan.com/moriya-takamatsu-symbol-tower/", parking:"なし（周辺の有料駐車場）", slug:"moriya-sunport" },
  { id:4, name:"はやし家製麺所 高松空港店", kana:"はやしや", city:"高松市", type:"一般", dish:"", hours:"8:00〜20:00", closed:"年中無休", parking:"高松空港の有料駐車場", slug:"hayashiya-takamatsu-airport" },
  { id:5, name:"さぬき麺業 高松空港店", kana:"さぬきめんぎょう", city:"高松市", type:"一般", dish:"", hours:"9:30〜19:30", closed:"年中無休", parking:"高松空港の有料駐車場", slug:"sanukimengyo-takamatsu-airport" },
  { id:6, name:"かわたうどん", kana:"かわた", city:"高松市", type:"一般", dish:"", hours:"10:00〜19:00", closed:"水曜日", parking:"あり", slug:"kawataudon" },
  { id:7, name:"讃岐うどん 空海房", kana:"くうかいぼう", city:"高松市", type:"セルフ", dish:"", hours:"6:30〜15:00", closed:"年中無休", blog:"https://kagawan.com/kukaibo/", parking:"あり（45台）", slug:"kuukaibou" },
  { id:8, name:"麺処 綿谷 高松店", kana:"わたや", city:"高松市", type:"セルフ", dish:"", hours:"8:30〜14:30（売り切れ次第終了）", closed:"日曜・祝日", blog:"https://kagawan.com/wataya/", parking:"なし", slug:"wataya" },
  { id:9, name:"根っこ 三谷店", kana:"ねっこ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜17:00", closed:"年中無休（1/1・1/2休）", blog:"https://kagawan.com/nekko-takamatsu/", parking:"あり（48台）", slug:"nekko-mitani" },
  { id:10, name:"根っこ 空港通り店", kana:"ねっこ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜16:00", closed:"年中無休", blog:"https://kagawan.com/nekko-takamatsu/", parking:"あり（46台）", slug:"nekko-airport" },
  { id:11, name:"根っこ 鬼無店", kana:"ねっこ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜16:00", closed:"年中無休（1/1・1/2休）", blog:"https://kagawan.com/nekko-takamatsu/", parking:"あり（24台）", slug:"nekko-kinashi" },
  { id:12, name:"セルフうどんの店 竹清", kana:"ちくせい", city:"高松市", type:"セルフ", dish:"", hours:"10:45〜14:30（売り切れ次第終了）", closed:"月・日曜", blog:"https://kagawan.com/chikusei-udon/", parking:"あり（専用7台＋コインP）", slug:"chikusei" },
  { id:13, name:"讃岐うどん 一福 国分寺本店", kana:"いっぷく", city:"高松市", type:"セルフ", dish:"", hours:"10:00〜14:00", closed:"金曜", blog:"https://kagawan.com/udon-ippuku/", parking:"あり（複数）", slug:"ippuku" },
  { id:14, name:"松下製麺所", kana:"まつしたせいめんじょ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜15:00", closed:"日曜日", parking:"あり", slug:"matsushitaseimenjo" },
  { id:15, name:"晴屋製麺所 今里店", kana:"はれや", city:"高松市", type:"セルフ", dish:"", hours:"10:00〜15:00", closed:"土曜", blog:"https://kagawan.com/hareya/", parking:"あり（13台）", slug:"hareya-imazato" },
  { id:16, name:"おうどん 瀬戸晴れ", kana:"せとばれ", city:"高松市", type:"一般", dish:"", hours:"9:00〜15:00（麺切れ次第終了）", closed:"木曜・第2・第4水曜", blog:"https://kagawan.com/setobare-oudon/", parking:"あり（2カ所・計30台）", slug:"setobare" },
  { id:17, name:"饂飩家 五右衛門", kana:"ごえもん", city:"高松市", type:"一般", dish:"", hours:"20:00〜翌1:00（LO0:30・売切れ次第終了）", closed:"日・月曜・祝日", blog:"https://kagawan.com/udonya-goemon/", parking:"なし", slug:"goemon" },
  { id:18, name:"手打ちうどん 鶴丸", kana:"つるまる", city:"高松市", type:"一般", dish:"", hours:"20:00〜翌2:00（麺切れ次第終了）", closed:"日・祝（GW/年末年始は変更あり）", blog:"https://kagawan.com/teuchiudon-tsurumaru/", parking:"なし", slug:"tsurumaru" },
  { id:19, name:"さか枝うどん 本店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜15:00", closed:"土・日・祝", blog:"https://kagawan.com/sakaeda-udon/", parking:"あり（無料4台＋近隣コインP）", slug:"sakaeda" },
  { id:20, name:"さか枝うどん 春日店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜15:00", closed:"年中無休", blog:"https://kagawan.com/sakaeda-udon/", parking:"あり（無料）", slug:"sakaeda-kasuga" },
  { id:21, name:"さか枝うどん 南新町店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜17:00", closed:"年中無休", blog:"https://kagawan.com/sakaeda-udon/", parking:"近隣にコインP", slug:"sakaeda-minamishinmachi" },
  { id:22, name:"さか枝 仏生山店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜16:00", closed:"年中無休", blog:"https://kagawan.com/sakaeda-udon/", parking:"あり（無料）", slug:"sakaeda-bushozan" },
  { id:23, name:"さか枝 多肥店", kana:"さかえだ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜15:00", closed:"年中無休", blog:"https://kagawan.com/sakaeda-udon/", parking:"あり（無料）", slug:"sakaeda-tahi" },
  { id:24, name:"ざいごうどん本家 わら家", kana:"わらや", city:"高松市", type:"一般", dish:"", hours:"9:30〜17:30", closed:"年中無休", blog:"https://kagawan.com/waraya/", parking:"あり（150台）", slug:"waraya" },
  { id:25, name:"うどん本陣 山田家", kana:"やまだや", city:"高松市", type:"一般", dish:"", hours:"10:00〜20:00", closed:"年中無休", blog:"https://kagawan.com/yamadaya/", parking:"あり（160台）", slug:"yamadaya" },
  { id:26, name:"手打ちうどん ひさ枝", kana:"ひさえ", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜14:00", closed:"年中無休", blog:"https://kagawan.com/hisaeda/", parking:"あり（約10台）", slug:"hisae" },
  { id:27, name:"ヨコクラうどん", kana:"よこくら", city:"高松市", type:"セルフ", dish:"", hours:"8:00〜14:00", closed:"木曜（不定休あり）", blog:"https://kagawan.com/yokokuraudon/", parking:"あり（約15台）", slug:"yokokura" },
  { id:28, name:"さぬきうどん 上原屋 本店", kana:"うえはらや", city:"高松市", type:"セルフ", dish:"", hours:"9:30〜14:30（売り切れ次第終了）", closed:"日曜", blog:"https://kagawan.com/ueharayahonten/", parking:"あり（18台）", slug:"ueharaya" },
  { id:29, name:"麺匠 くすがみ", kana:"くすがみ", city:"高松市", type:"一般", dish:"", hours:"10:00〜14:30", closed:"火曜", blog:"https://kagawan.com/kusugami/", parking:"あり（12台）", slug:"kusugami" },
  { id:30, name:"あづまうどん", kana:"あづま", city:"高松市", type:"セルフ", dish:"", hours:"11:00〜14:00（麺切れ次第終了）", closed:"水曜", blog:"https://kagawan.com/azumaudon/", parking:"あり（約30台）", slug:"azuma" },
  { id:31, name:"うつ海うどん", kana:"うつみ", city:"高松市", type:"セルフ", dish:"", hours:"6:00〜15:00（売り切れ次第終了）", closed:"火曜", blog:"https://kagawan.com/utsumiudon/", parking:"あり（無料・約20台）", slug:"utsumi" },
  { id:32, name:"高松満福", kana:"まんぷく", city:"高松市", type:"セルフ", dish:"", hours:"平日 10:00〜14:00／土日祝 9:00〜14:00", closed:"火曜（祝日は営業）", blog:"https://kagawan.com/manpukuudon/", parking:"あり（40台）", slug:"manpuku" },
  { id:33, name:"手打うどん 三徳", kana:"さんとく", city:"高松市", type:"セルフ", dish:"", hours:"11:00〜16:00（LO15:45）", closed:"木曜・第4水曜", blog:"https://kagawan.com/santoku/", parking:"あり（30台）", slug:"santoku" },
  { id:34, name:"中西うどん", kana:"なかにし", city:"高松市", type:"セルフ", dish:"", hours:"9:00〜15:00（玉切れ次第終了）", closed:"火曜", blog:"https://kagawan.com/nakanishiudon/", parking:"あり（無料50台）", slug:"nakanishi" },
  { id:35, name:"手打ちうどん 清水屋", kana:"しみずや", city:"高松市", type:"セルフ", dish:"", hours:"10:00〜14:00（麺切れ次第終了）", closed:"日曜", blog:"https://kagawan.com/shimizuya/", parking:"あり（共同・多数）", slug:"shimizuya" },
  { id:36, name:"宮武うどん", kana:"みやたけ", city:"高松市", type:"セルフ", dish:"", hours:"9:30〜15:00（玉切れ次第終了）", closed:"水曜", blog:"https://kagawan.com/miyatakeudon/", parking:"あり（25台）", slug:"miyatake" },
  { id:37, name:"UDON 山もり", kana:"やまもり", city:"高松市", type:"セルフ", dish:"", hours:"11:00〜15:30", closed:"水曜（祝日は営業・翌日休）", blog:"https://kagawan.com/yamamori/", parking:"あり（13台）", slug:"yamamori" },
  { id:38, name:"手打麺や 大島", kana:"おおしま", city:"高松市", type:"セルフ", dish:"", hours:"9:30〜15:00", closed:"第1・第3・第5日曜・1/1〜4", blog:"https://kagawan.com/teuchimenya-oshima/", parking:"あり（20台）", slug:"ooshima" },
  { id:39, name:"がもううどん", kana:"がもう", city:"坂出市", type:"セルフ", dish:"", hours:"平日 8:30〜14:00／土・祝 8:30〜13:00（売切れ次第終了）", closed:"月・日曜（臨時休あり）", blog:"https://kagawan.com/gamoudon/", parking:"あり（54台・3カ所）", slug:"gamou" },
  { id:40, name:"日の出製麺所", kana:"ひので", city:"坂出市", type:"製麺所", dish:"", hours:"うどん 11:30〜12:30／土産 9:00〜16:00", closed:"不定休", blog:"https://kagawan.com/hinode-udon/", parking:"あり（多数・土日祝は北側30台開放）", slug:"hinode" },
  { id:41, name:"山下うどん", kana:"やました", city:"坂出市", type:"セルフ", dish:"", hours:"8:30〜15:00", closed:"月・日曜", blog:"https://kagawan.com/yamashitaudon-sakaide/", parking:"あり（25台）", slug:"yamashita" },
  { id:42, name:"めんや七福 別邸", kana:"しちふく", city:"坂出市", type:"一般", dish:"", hours:"10:00〜15:00（麺切れ次第終了）", closed:"水曜", blog:"https://kagawan.com/menyashichifuku/", parking:"あり（40台）", slug:"shichifuku" },
  { id:43, name:"讃岐うどん やなぎ屋 西大浜店", kana:"やなぎや", city:"坂出市", type:"セルフ", dish:"", hours:"6:00〜20:00", closed:"日曜", blog:"https://kagawan.com/yanagiya/", parking:"あり（約30台）", slug:"yanagiya" },
  { id:44, name:"架け橋 夢うどん", kana:"ゆめ", city:"坂出市", type:"セルフ", dish:"", hours:"平日 10:00〜16:00／土日祝 10:00〜17:00", closed:"年中無休", blog:"https://kagawan.com/yume-udon/", parking:"あり（与島PA内）", slug:"yume" },
  { id:45, name:"山越うどん", kana:"やまごえ", city:"綾川町", type:"セルフ", dish:"", hours:"9:00〜13:30", closed:"水・日曜（GW/盆/正月は臨時休あり）", blog:"https://kagawan.com/yamagoeudon/", parking:"あり（200台）", slug:"yamagoeudon" },
  { id:46, name:"手打うどん田村", kana:"たむら", city:"綾川町", type:"セルフ", dish:"", hours:"9:00〜13:00（売り切れ次第終了）", closed:"日曜・祝日", blog:"https://kagawan.com/tamuraudon/", parking:"あり（30台）", slug:"tamuraudon" },
  { id:47, name:"本格手打うどん はゆか", kana:"はゆか", city:"綾川町", type:"セルフ", dish:"", hours:"10:00〜15:30", closed:"月曜（祝日は営業）", blog:"https://kagawan.com/hayuka/", parking:"あり（23台）", slug:"hayuka" },
  { id:48, name:"池内うどん店", kana:"いけうち", city:"綾川町", type:"製麺所", dish:"", hours:"7:00〜13:00（売り切れ次第終了）", closed:"月・金曜", blog:"https://kagawan.com/ikeuchiudonten/", parking:"あり（店の東側倉庫前）", slug:"ikeuchiudonten" },
  { id:49, name:"いなもくうどん", kana:"いなもく", city:"綾川町", type:"セルフ", dish:"", hours:"10:30〜14:00（玉切れ次第終了）", closed:"木曜・第2水曜（祝日は営業・翌日休）", blog:"https://kagawan.com/inamokuudon/", parking:"あり（10台）", slug:"inamokuudon" },
  { id:50, name:"釜あげうどん 長田 in 香の香", kana:"ながた", city:"善通寺市", type:"一般", dish:"", hours:"9:00〜15:00（玉切れの際は早じまい）", closed:"水・木曜（祝日は営業）", blog:"https://kagawan.com/nagata-in-kanoka/", parking:"あり（160台・大型バス可）", slug:"nagata-in-kanoka" },
  { id:51, name:"山下うどん", kana:"やました", city:"善通寺市", type:"セルフ", dish:"", hours:"9:30〜16:00（売り切れ次第終了）", closed:"火曜（祝日は営業・翌水曜休）", blog:"https://kagawan.com/yamashitaudon-zentsuji/", parking:"あり（50台）", slug:"yamashitaudon-zentsuji" },
  { id:52, name:"宮川製麺所", kana:"みやがわ", city:"善通寺市", type:"製麺所", dish:"", hours:"8:00〜18:00（売り切れ次第終了）", closed:"日曜", blog:"https://kagawan.com/miyagawa-seimenjyo/", parking:"あり（30台）", slug:"miyagawa-seimenjyo" },
  { id:53, name:"白川うどん", kana:"しらかわ", city:"善通寺市", type:"セルフ", dish:"", hours:"9:30〜15:00（売り切れ次第終了）", closed:"火曜（祝日は営業・翌日休）・第3水曜", blog:"https://kagawan.com/sirakawaudon/", parking:"あり（30台）", slug:"sirakawaudon" },
  { id:54, name:"本格手打 あかみち", kana:"あかみち", city:"善通寺市", type:"一般", dish:"", hours:"10:00〜15:00（玉切れ次第終了）※一部土曜は夜18:00〜20:00", closed:"水・木曜", blog:"https://kagawan.com/akamichi/", parking:"あり（25台）", slug:"akamichi" },
  { id:55, name:"セルフうどん こだわり八輻", kana:"こだわりやわら", city:"善通寺市", type:"セルフ", dish:"", hours:"11:00〜14:00", closed:"火・金曜", blog:"https://kagawan.com/hachiya/", parking:"あり（30台）", slug:"hachiya" },
  { id:56, name:"あやうた製麺", kana:"あやうた", city:"丸亀市", type:"セルフ", dish:"", hours:"11:00〜14:00", closed:"金曜", blog:"https://kagawan.com/ayautaseimen/", parking:"あり（25台）", slug:"ayautaseimen" },
  { id:57, name:"麦香うどん", kana:"むぎか", city:"丸亀市", type:"一般", dish:"", hours:"10:00〜15:00", closed:"水曜", blog:"https://kagawan.com/bakuka-udon/", parking:"あり（15台）", slug:"bakuka-udon" },
  { id:58, name:"讃岐うどん海侍其の壱", kana:"かいじ", city:"丸亀市", type:"セルフ", dish:"", hours:"9:00〜14:00", closed:"月曜（祝日は翌火曜）", blog:"https://kagawan.com/kaiji/", parking:"あり（店舗横）", slug:"kaiji" },
  { id:59, name:"純手打うどん よしや", kana:"よしや", city:"丸亀市", type:"セルフ", dish:"", hours:"7:00〜14:50（売り切れ次第終了）", closed:"火曜", blog:"https://kagawan.com/jyunteuchiudon-yoshiya/", parking:"あり（15台）", slug:"jyunteuchiudon-yoshiya" },
  { id:60, name:"セルフうどん おかだ", kana:"おかだ", city:"丸亀市", type:"セルフ", dish:"", hours:"飲食 10:30〜14:00／土産 9:00〜17:00", closed:"土・日・祝", blog:"https://kagawan.com/selfudonokada/", parking:"あり（33台）", slug:"selfudonokada" },
  { id:61, name:"なかむらうどん", kana:"なかむら", city:"丸亀市", type:"セルフ", dish:"", hours:"9:00〜14:00", closed:"火曜", blog:"https://kagawan.com/hiragana-nakamuraudon/", parking:"あり（40台）", slug:"hiragana-nakamuraudon" },
  { id:62, name:"麺処 綿谷 丸亀店", kana:"わたや", city:"丸亀市", type:"セルフ", dish:"", hours:"8:30〜14:00（売り切れ次第終了）", closed:"日曜・祝日", blog:"https://kagawan.com/wataya/", parking:"あり（50台）", slug:"wataya-62" },
  { id:63, name:"元祖しょうゆうどん 小縣家", kana:"おがたや", city:"まんのう町", type:"一般", dish:"", hours:"10:30〜14:30", closed:"月・火曜", blog:"https://kagawan.com/ogataya/", parking:"あり（40台）", slug:"ogataya" },
  { id:64, name:"谷川米穀店", kana:"たにがわ", city:"まんのう町", type:"セルフ", dish:"", hours:"10:30〜13:30", closed:"日曜", blog:"https://kagawan.com/tanikawabeikokuten/", parking:"あり", slug:"tanikawabeikokuten" },
  { id:65, name:"三嶋製麺所", kana:"みしま", city:"まんのう町", type:"製麺所", dish:"", hours:"平日 9:00〜16:30／土日 9:00〜16:00", closed:"金曜", blog:"https://kagawan.com/mishimaseimenjo/", parking:"あり（3台）", slug:"mishimaseimenjo" },
  { id:66, name:"山内うどん", kana:"やまうち", city:"まんのう町", type:"セルフ", dish:"", hours:"9:00〜13:30（玉切れ次第終了）", closed:"木曜", blog:"https://kagawan.com/yamauchiudon/", parking:"あり（約30台）", slug:"yamauchiudon" },
  { id:67, name:"うどん そらいけ", kana:"そらいけ", city:"さぬき市", type:"セルフ", dish:"", hours:"11:00〜14:00", closed:"日曜", blog:"https://kagawan.com/soraike/", parking:"あり（3台）", slug:"soraike" },
  { id:68, name:"さぬきうどん羽立", kana:"はだち", city:"さぬき市", type:"一般", dish:"", hours:"10:00〜14:00", closed:"金曜", blog:"https://kagawan.com/haryu/", parking:"あり（8台）", slug:"haryu" },
  { id:69, name:"さぬきうどん 溜", kana:"たまり", city:"さぬき市", type:"セルフ", dish:"", hours:"10:00〜15:00", closed:"年中無休", blog:"https://kagawan.com/tamariudon/", parking:"あり（無料・約150台）", slug:"tamariudon" },
  { id:70, name:"八十八庵", kana:"やそばあん", city:"さぬき市", type:"一般", dish:"", hours:"8:00〜16:30（LO16:00）", closed:"12/30・31のみ休み", blog:"https://kagawan.com/yasobaan/", parking:"あり（60台）", slug:"yasobaan" },
  { id:71, name:"さぬきうどん処 麺でぃ〜", kana:"めんでぃ", city:"さぬき市", type:"セルフ", dish:"", hours:"10:30〜15:00", closed:"月曜（祝日は営業・翌火曜休）", blog:"https://kagawan.com/udondokoro-mendy/", parking:"あり（3カ所）", slug:"udondokoro-mendy" },
  { id:72, name:"麺処 まはろ", kana:"まはろ", city:"さぬき市", type:"一般", dish:"", hours:"平日 11:00〜14:00／土日祝 10:30〜15:00（玉切れ次第終了）", closed:"水曜（祝日は営業・翌木曜休）", blog:"https://kagawan.com/maharo/", parking:"あり（無料・約20台）", slug:"maharo" },
  { id:73, name:"手打うどん まるたけ", kana:"まるたけ", city:"さぬき市", type:"セルフ", dish:"", hours:"9:00〜15:00", closed:"土・日曜", blog:"https://kagawan.com/marutakeudon/", parking:"あり（13台）", slug:"marutakeudon" },
  { id:74, name:"手打うどん 源内", kana:"てうちうどん げんない", city:"さぬき市", type:"一般", dish:"", hours:"10:00〜19:00（売切れ次第終了）", closed:"月曜日", parking:"あり", slug:"gennai" },
  { id:75, name:"松原うどん", kana:"まつばらうどん", city:"さぬき市", type:"セルフ", dish:"", hours:"10:30〜15:00", closed:"年中無休", parking:"あり", slug:"matsubaraudon" },
  { id:76, name:"あなぶき家 津田の松原SA 上り線", kana:"あなぶきや つだのまつばらさーびすえりあ のぼりせん", city:"さぬき市", type:"セルフ", dish:"", hours:"7:00〜21:00", closed:"年中無休", parking:"あり", slug:"anabukiya" },
  { id:77, name:"須崎食料品店", kana:"すさき", city:"三豊市", type:"セルフ", dish:"", hours:"9:00〜11:30", closed:"水曜（臨時休業あり）", blog:"https://kagawan.com/suzakishokuryohinten/", parking:"あり（約38台）", slug:"suzakishokuryohinten" },
  { id:78, name:"うどんや カマ喜ri", kana:"かまきり", city:"観音寺市", type:"一般", dish:"", hours:"11:00〜14:00（玉切れ次第終了）", closed:"日曜", blog:"https://kagawan.com/kamakiri/", parking:"あり（約20台）", slug:"kamakiri" },
  { id:79, name:"うまじ家 豊浜店", kana:"うまじや", city:"観音寺市", type:"セルフ", dish:"", hours:"10:00〜13:30", closed:"なし", blog:"https://kagawan.com/umajiya-toyohama/", parking:"あり（19台）", slug:"umajiya-toyohama" },
  { id:80, name:"手織うどん 滝音", kana:"たきおと", city:"三木町", type:"セルフ", dish:"", hours:"10:00〜15:00", closed:"月曜（祝日は営業・翌火曜休）", blog:"https://kagawan.com/takine/", parking:"あり（64台）", slug:"takine" },
  { id:81, name:"多田製麺所", kana:"ただ", city:"三木町", type:"製麺所", dish:"", hours:"8:00〜15:00", closed:"火曜", blog:"https://kagawan.com/tadaseimenjo/", parking:"あり（第一3台・第二あり）", slug:"tadaseimenjo" },
  { id:82, name:"めりけんや 高松駅前店", kana:"めりけんやたかまつえきまえてん", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜20:00", closed:"年中無休", parking:"なし", slug:"merikenya-takamatsu" },
  { id:83, name:"めりけんや サンポート店", kana:"めりけんやさんぽーとてん", city:"高松市", type:"セルフ", dish:"", hours:"11:00〜14:00", closed:"土曜日・日曜日", parking:"なし", slug:"merikenya-sunport" },
  { id:84, name:"めりけんや かけはし店", kana:"めりけんやかけはしてん", city:"宇多津町", type:"セルフ", dish:"", hours:"9:00〜15:00", closed:"年中無休", parking:"あり", slug:"merikenya-kakehashi" },
  { id:85, name:"めりけんや 丸亀店", kana:"めりけんやまるがめてん", city:"丸亀市", type:"セルフ", dish:"", hours:"月〜金 9:00〜15:00、土日 7:00〜15:00", closed:"年中無休", parking:"あり", slug:"merikenya-marugame" },
  { id:86, name:"うどん亭 いわせ", kana:"いわせ", city:"さぬき市", type:"一般", dish:"", hours:"10:30〜19:00", closed:"日曜日・月曜日", parking:"あり", slug:"iwase" },
  { id:87, name:"手打ちうどん 古奈や", kana:"こなや", city:"高松市", type:"セルフ", dish:"", hours:"7:00〜15:00", closed:"日曜日", parking:"あり", slug:"konaya" },
  { id:88, name:"ふる里うどん", kana:"ふるさと", city:"高松市", type:"セルフ", dish:"", hours:"11:00〜15:00", closed:"水曜日", parking:"あり", slug:"furusato" },
  { id:89, name:"手打ちうどん 上田", kana:"うえだ", city:"高松市", type:"セルフ", dish:"", hours:"9:00〜14:00", closed:"月曜日", parking:"あり", slug:"teuchiudon-ueda" },
  { id:90, name:"吉本食品", kana:"よしもとしょくひん", city:"東かがわ市", type:"製麺所", dish:"", hours:"8:00〜14:00", closed:"日曜日", parking:"あり（15台）", slug:"yoshimotoshokuhin" },
  { id:91, name:"山賊村", kana:"さんぞくむら", city:"東かがわ市", type:"一般", dish:"", hours:"11:00〜14:00（日曜日のみ14:30まで営業）", closed:"月曜日・土曜日", parking:"あり（15台）", slug:"sanzokumura" },
  { id:92, name:"麺工房 六車", kana:"むぐるま", city:"東かがわ市", type:"一般", dish:"", hours:"11:00〜13:30", closed:"月曜日", parking:"あり（20台）", slug:"muguruma" },
  { id:93, name:"本場さぬき うどんや", kana:"うどんや", city:"東かがわ市", type:"セルフ", dish:"", hours:"9:15〜15:00", closed:"年中無休", parking:"あり（20台）", slug:"udonya" },
  { id:94, name:"マルタツ手打ちうどん 伊座本店", kana:"まるたつ", city:"東かがわ市", type:"一般", dish:"", hours:"8:00〜14:30", closed:"水曜日・土曜日・日曜日", parking:"あり（30台）", slug:"marutatsu" },
  { id:95, name:"元匠 湊店", kana:"げんしょうみなと", city:"東かがわ市", type:"セルフ", dish:"", hours:"6:00〜15:00", closed:"年中無休", parking:"あり（80台）", slug:"gensho-minato" },
  { id:96, name:"元匠 東かがわ店", kana:"げんしょうひがしかがわ", city:"東かがわ市", type:"セルフ", dish:"", hours:"平日11:00〜14:00・土日祝10:00〜15:00", closed:"年中無休", parking:"あり（40台）", slug:"gensho-higashikagawa" },
  { id:97, name:"手打ちうどん もとい", kana:"もとい", city:"東かがわ市", type:"一般", dish:"", hours:"11:00〜14:00", closed:"日曜日", parking:"あり（14台）", slug:"motoi" },
  { id:98, name:"うどん亭 よだ", kana:"よだ", city:"東かがわ市", type:"一般", dish:"", hours:"11:30〜14:00", closed:"月曜日〜木曜日", parking:"あり", slug:"yoda" },
  { id:99, name:"手打ちうどん むさし", kana:"むさし", city:"琴平町", type:"一般", dish:"", hours:"10:00〜15:00／17:00〜20:00", closed:"月・火曜", blog:"https://kagawan.com/musashi/", parking:"あり（無料・共同195台）", slug:"musashi" },
  { id:100, name:"こんぴらうどん 表参道店", kana:"こんぴらうどん", city:"琴平町", type:"一般", dish:"", hours:"平日10:00〜16:00／土日祝9:00〜16:00", closed:"年中無休", blog:"https://kagawan.com/udon-kotohira/", parking:"あり（無料）", slug:"konpiraudon-sando" },
  { id:101, name:"こんぴらうどん 工場店", kana:"こんぴらうどん", city:"琴平町", type:"一般", dish:"", hours:"8:00〜15:00", closed:"火〜金曜", blog:"https://kagawan.com/udon-kotohira/", parking:"あり（3台）", slug:"konpiraudon-kojo" },
  { id:102, name:"こんぴらうどん 北店", kana:"こんぴらうどん", city:"琴平町", type:"一般", dish:"", hours:"8:00〜16:00", closed:"月〜金曜", blog:"https://kagawan.com/udon-kotohira/", parking:"なし", slug:"konpiraudon-kita" },
  { id:103, name:"手打ちうどん てんてこ舞", kana:"てんてこまい", city:"琴平町", type:"一般", dish:"", hours:"9:30〜16:00", closed:"水曜", blog:"https://kagawan.com/udon-kotohira/", parking:"あり（有料）", slug:"tentekomai" },
  { id:104, name:"セルフうどん いわのや", kana:"いわのや", city:"琴平町", type:"セルフ", dish:"", hours:"10:30〜15:00", closed:"日曜", blog:"https://kagawan.com/udon-kotohira/", parking:"あり（無料）", slug:"iwanoya" },
  { id:105, name:"虎屋うどん", kana:"とらやうどん", city:"琴平町", type:"一般", dish:"", hours:"9:00〜16:00", closed:"年中無休", blog:"https://kagawan.com/udon-kotohira/", parking:"なし", slug:"torayaudon" },
  { id:106, name:"讃岐うどん めん舟", kana:"めんふね", city:"琴平町", type:"一般", dish:"", hours:"火〜金10:00〜14:00／土日10:00〜15:00", closed:"月曜", blog:"https://kagawan.com/udon-kotohira/", parking:"あり", slug:"menfune" },
  { id:107, name:"はなまるうどん 高松兵庫町店", kana:"はなまるうどん たかまつひょうごまちてん", city:"高松市", type:"セルフ", dish:"", hours:"10:00-21:30", closed:"年中無休", parking:"あり", slug:"hanamaruudon-takamatsu-hyogomachi" },
  { id:108, name:"はなまるうどん 高松円座店", kana:"はなまるうどん たかまつえんざてん", city:"高松市", type:"セルフ", dish:"", hours:"10:00-21:30", closed:"年中無休", parking:"あり", slug:"hanamaruudon-takamatsu-enza" },
  { id:109, name:"はなまるうどん×吉野家 ゆめタウン高松店", kana:"はなまるうどんよしのや ゆめたうんたかまつてん", city:"高松市", type:"セルフ", dish:"", hours:"10:00-21:00", closed:"年中無休", parking:"あり", slug:"hanamaruudon-yoshinoya-yume-town-takamatsu" },
  { id:110, name:"はなまるうどん 多肥店", kana:"はなまるうどん たひてん", city:"高松市", type:"セルフ", dish:"", hours:"【平日】10:00-21:00【土日】7:00-21:00", closed:"年中無休", parking:"あり", slug:"hanamaruudon-tahi" },
  { id:111, name:"はなまるうどん 田町店", kana:"はなまるうどん たまちてん", city:"高松市", type:"セルフ", dish:"", hours:"10:00-21:30", closed:"年中無休", parking:"あり", slug:"hanamaruudon-tamachi" },
  { id:112, name:"はなまるうどん TKMT本店", kana:"はなまるうどん たかまつほんてん", city:"高松市", type:"セルフ", dish:"", hours:"2026年7月中旬オープン予定", closed:"年中無休", parking:"あり", slug:"hanamaruudon-tkmt-honten" },
  { id:113, name:"はなまるうどん 高松三条店", kana:"はなまるうどん たかまつさんじょうてん", city:"高松市", type:"セルフ", dish:"", hours:"10:00-21:30", closed:"年中無休", parking:"あり", slug:"hanamaruudon-takamatsu-sanjo" },
  { id:114, name:"はなまるうどん 高松中央インター店", kana:"はなまるうどん たかまつちゅうおういんたーてん", city:"高松市", type:"セルフ", dish:"", hours:"10:00-22:00", closed:"年中無休", parking:"あり", slug:"hanamaruudon-takamatsu-chuo-inter" },
  { id:115, name:"はなまるうどん 丸亀城西店", kana:"はなまるうどん まるがめじょうせいてん", city:"丸亀市", type:"セルフ", dish:"", hours:"10:00-22:00", closed:"年中無休", parking:"あり", slug:"hanamaruudon-marugame-jonishi" },
  { id:116, name:"はなまるうどん イオンモール綾川店", kana:"はなまるうどん いおんもーるあやがわてん", city:"綾川町", type:"セルフ", dish:"", hours:"10:00-21:00", closed:"年中無休", parking:"あり", slug:"hanamaruudon-aeon-mall-ayagawa" },
  { id:117, name:"はなまるうどん ゆめタウン三豊店", kana:"はなまるうどん ゆめたうんみとよてん", city:"三豊市", type:"セルフ", dish:"", hours:"10:00-20:00", closed:"年中無休", parking:"あり", slug:"hanamaruudon-yume-town-mitoyo" },
  { id:118, name:"はなまるうどん×吉野家 マルナカ観音寺駅南店", kana:"はなまるうどんよしのや まるなかかんおんじえきみなみてん", city:"観音寺市", type:"セルフ", dish:"", hours:"10:00-21:30", closed:"年中無休", parking:"あり", slug:"hanamaruudon-yoshinoya-marunaka-kanonji-eki-minami" },
  { id:119, name:"はなまるうどん 志度店", kana:"はなまるうどん しどてん", city:"さぬき市", type:"セルフ", dish:"", hours:"10:00-22:00", closed:"年中無休", parking:"あり", slug:"hanamaruudon-shido" },
  { id:120, name:"はなまるうどん 坂出白金店", kana:"はなまるうどん さかいでしろがねてん", city:"坂出市", type:"セルフ", dish:"", hours:"10:30-20:30", closed:"年中無休", parking:"あり", slug:"hanamaruudon-sakaide-shirogane" },
  { id:121, name:"いけこうどん", kana:"いけこ", city:"多度津町", type:"一般", dish:"", hours:"10:00〜15:00", closed:"月曜", blog:"https://kagawan.com/ikekoudon/", parking:"あり（約14台）", slug:"ikekoudon" },
  { id:122, name:"釜出しさぬきうどんめん一", kana:"めんいち", city:"多度津町", type:"セルフ", dish:"", hours:"10:30〜15:00", closed:"年中無休", parking:"あり", slug:"menichi" },
  { id:123, name:"中村うどん", kana:"なかむらうどん", city:"丸亀市", type:"セルフ", dish:"", hours:"10:00〜14:00（玉切れ次第終了）", closed:"金曜日", parking:"あり", slug:"kanji-nakamuraudon" },
  { id:124, name:"手打ちうどん 歩", kana:"てうちうどん あゆみ", city:"丸亀市", type:"一般", dish:"", hours:"10:30〜17:00", closed:"火曜日（祝日の場合は営業）", parking:"あり", slug:"ayumi" },
  { id:125, name:"手打うどん まごころ", kana:"てうちうどん まごころ", city:"丸亀市", type:"セルフ", dish:"", hours:"6:00〜16:00", closed:"元日のみ", parking:"あり", slug:"magokoro" },
  { id:126, name:"手打うどん 飯野屋", kana:"てうちうどん いいのや", city:"丸亀市", type:"一般", dish:"", hours:"9:00〜15:00", closed:"月曜日・第4火曜日", parking:"あり", slug:"iinoya" },
  { id:127, name:"手打ちうどん 山とも", kana:"てうちうどん やまとも", city:"丸亀市", type:"セルフ", dish:"", hours:"9:00〜14:00（玉切れ次第終了）", closed:"日曜日", parking:"あり", slug:"teuchiudon-yamatomo" },
  { id:128, name:"セルフうどん かまや", kana:"せるふうどん かまや", city:"坂出市", type:"セルフ", dish:"", hours:"9:00〜15:00", closed:"木曜日", parking:"あり", slug:"self-udon-kamaya" },
  { id:129, name:"セルフうどんさぬきまるふじ 本店", kana:"せるふうどんさぬきまるふじ ほんてん", city:"坂出市", type:"セルフ", dish:"", hours:"10:00〜15:00", closed:"水曜日", parking:"あり", slug:"self-udon-sanuki-marufuji-honten" },
  { id:130, name:"手打うどん 町川", kana:"てうちうどん まちかわ", city:"坂出市", type:"一般", dish:"", hours:"10:00〜14:00", closed:"月曜日", parking:"あり", slug:"teuchi-udon-machikawa" },
  { id:131, name:"いきいきうどん 坂出店", kana:"いきいきうどん さかいでてん", city:"坂出市", type:"セルフ", dish:"", hours:"5:00〜15:30", closed:"元日のみ", parking:"あり", slug:"ikiikiudon-sakaide" },
  { id:132, name:"川川うどん", kana:"かわかわうどん", city:"善通寺市", type:"一般", dish:"", hours:"11:00～14:00（玉切れ次第終了）", closed:"火曜日・水曜日", parking:"あり", slug:"kawakawaudon" },
  { id:133, name:"さぬきうどん穂の花", kana:"さぬきうどん ほのはな", city:"善通寺市", type:"セルフ", dish:"", hours:"10:30〜14:30（土日祝は15:00）", closed:"木曜日", parking:"あり", slug:"honoka" },
  { id:134, name:"善通寺・四國館", kana:"ぜんつうじ・しこくかん", city:"善通寺市", type:"一般", dish:"", hours:"10:00～16:00", closed:"不定休", parking:"あり", slug:"zentsuji-shikokukan" },
  { id:135, name:"ジャンボうどん 高木", kana:"じゃんぼうどん たかぎ", city:"善通寺市", type:"一般", dish:"", hours:"8:30〜14:00（玉切れ次第終了）", closed:"日曜日・祝日", parking:"あり", slug:"jumbo-udon-takagi" },
  { id:136, name:"三好うどん", kana:"みよしようどん", city:"三豊市", type:"一般", dish:"", hours:"10:00〜14:00", closed:"日曜日・祝日", parking:"あり", slug:"miyoshi-udon" },
  { id:137, name:"SIRAKAWA", kana:"しらかわ", city:"三豊市", type:"一般", dish:"", hours:"11:00〜13:30", closed:"月曜日", parking:"あり", slug:"sirakawa" },
  { id:138, name:"手打ちうどん 渡辺", kana:"てうちうどん わたなべ", city:"三豊市", type:"一般", dish:"", hours:"10:30〜15:00", closed:"木曜日", parking:"あり", slug:"teuchi-udon-watanabe" },
  { id:139, name:"上杉食品", kana:"うえすぎしょくひん", city:"三豊市", type:"セルフ", dish:"", hours:"6:30〜8:00（土日は9:00まで）", closed:"月曜日・第1火曜日", parking:"あり", slug:"uesugishokuhin" },
  { id:140, name:"本格手打ちうどん もり", kana:"ほんかくてうちうどん もり", city:"三豊市", type:"一般", dish:"", hours:"10:00〜14:00", closed:"火曜日", parking:"あり", slug:"honkaku-teuchi-udon-mori" },
  { id:141, name:"松ゆき", kana:"まつゆき", city:"三豊市", type:"一般", dish:"", hours:"10:00〜15:00（麺売切れ次第終了）", closed:"火曜日・第2水曜日", parking:"あり", slug:"matsuyuki" },
  { id:142, name:"はすい亭", kana:"はすいてい", city:"三豊市", type:"セルフ", dish:"", hours:"10:30〜14:30", closed:"月曜日", parking:"あり", slug:"hasuitei" },
  { id:143, name:"本場かなくま餅 福田", kana:"ほんばかなくまもち ふくだ", city:"観音寺市", type:"一般", dish:"", hours:"10:00〜14:00", closed:"月曜日", parking:"あり", slug:"kanakumamochi-fukuda" },
  { id:144, name:"かなくま餅 11号線", kana:"かなくまもち じゅういちごうせん", city:"観音寺市", type:"一般", dish:"", hours:"8:00〜15:00", closed:"日曜日・第1・3木曜日", parking:"あり", slug:"kanakumamochi-route11" },
  { id:145, name:"西端手打 上戸", kana:"にしはしてうち じょうと", city:"観音寺市", type:"セルフ", dish:"", hours:"6:00〜14:00（麺売切れ次第終了）", closed:"木曜日（不定休あり）", parking:"あり", slug:"joto" },
  { id:146, name:"つるや", kana:"つるや", city:"観音寺市", type:"一般", dish:"", hours:"10:00〜20:00", closed:"火曜日", parking:"あり", slug:"tsuruya" },
  { id:147, name:"手打ちうどん 大喜多", kana:"てうちうどん おおきた", city:"観音寺市", type:"一般", dish:"", hours:"9:30〜14:30", closed:"土曜日・日曜日", parking:"あり", slug:"okita" },
  { id:148, name:"かじまや", kana:"かじまや", city:"観音寺市", type:"一般", dish:"", hours:"11:00〜16:00", closed:"月曜日", parking:"あり", slug:"kajimaya" },
  { id:149, name:"うどん好き", kana:"うどんずき", city:"観音寺市", type:"一般", dish:"", hours:"11:00〜14:00（土日は5:30〜8:30も営業）", closed:"火曜日", parking:"あり", slug:"udonzuki" },
  { id:150, name:"本格手打うどん おか泉", kana:"ほんかくてうちうどん おかせん", city:"宇多津町", type:"一般", dish:"", hours:"11:00〜20:00", closed:"月曜日・火曜日", parking:"あり", slug:"okasen" },
  { id:151, name:"うぶしな", kana:"うぶしな", city:"宇多津町", type:"セルフ", dish:"", hours:"11:00〜15:00", closed:"水曜日", parking:"あり", slug:"ubushina" },
  { id:152, name:"さぬきうどん 塩がま屋", kana:"さぬきうどん しおがまや", city:"宇多津町", type:"一般", dish:"", hours:"11:00〜20:30", closed:"水曜日", parking:"あり", slug:"shiogamaya" },
  { id:153, name:"讃岐うどん むぎ", kana:"さぬきうどん むぎ", city:"宇多津町", type:"セルフ", dish:"", hours:"10:00〜14:30", closed:"火曜日・金曜日", parking:"あり", slug:"sanukiudon-mugi" },
  { id:154, name:"長楽", kana:"ちょうらく", city:"宇多津町", type:"一般", dish:"", hours:"11:00〜14:00頃（麺売切れ次第終了）", closed:"水曜日・木曜日", parking:"あり", slug:"choraku" },
  { id:155, name:"情熱うどん わらく", kana:"わらく", city:"高松市", type:"一般", dish:"", hours:"10:30〜16:00", closed:"水曜日", parking:"あり", slug:"waraku" },
  { id:156, name:"橋本製麺所", kana:"はしもとせいめんじょ", city:"高松市", type:"製麺所", dish:"", hours:"10:00〜18:00", closed:"年中無休", parking:"なし", slug:"hashimoto-seimenjo" },
];
